# Generated by Django 3.1.2 on 2020-10-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
